app:
  id: java-myblog-api
apollo:
  meta: http://172.16.57.110:8080
  bootstrap:
    enabled: true
    namespaces: application
    eagerLoad:
      enabled: true
logging:
  level:
    com:
      weylau:
        javamyblogapi:
          controller:
            front: debug
feign:
  okhttp:
    enabled: true
spring:
  profiles:
    active: dev
    
server:
  servlet:
    context-path: /

mybatis:
  type-aliases-package: com.weylau.javamyblogapi.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*.xml

pagehelper:
  offset-as-page-num: true
  reasonable: true
  # size传0返回所有
  page-size-zero: true
  support-methods-arguments: true

